Imporved bash in bin/, also fully committed to bash
Also:
- quoting
- conditionals
- renaming

diff --git a/bin/remind b/bin/remind
--- a/bin/remind
+++ b/bin/remind
@@ -8,12 +8,12 @@ no_active_tmux_session=21
 
 usage() {
     cat << EOF
-Usage: remind [-h] [-c COLOR] MESSAGE [MESSAGE ...]
-Display popup in the active tmux session.
+Usage: remind [OPTION]... MESSAGE...
+Display a popup reminder in the active tmux session.
 
 Options:
   -h, --help           display this help and exit
-  -c, --color COLOR    set popup color; can be red, green, or blue (default)
+  -c, --color COLOR    set reminder color; can be red, green, or blue (default)
 
 Exit status:
   0     everything OK,
@@ -76,7 +76,7 @@ display_popup() {
     message="$@"
     max_length=80
     if [[ ${#message} -gt $max_length ]]; then
-        echo "ERROR: message is longer than $max_length characters ..." >&2
+        echo "ERROR: Message is longer than $max_length characters ..." >&2
         return $message_too_long
     fi
 
@@ -94,13 +94,13 @@ display_popup() {
 EOF
 )
 
-    active_session=$(tmux list-sessions | grep "(attached)$" | cut -d ":" -f 1)
+    active_session=$(tmux list-sessions | grep '(attached)$' | cut -d ':' -f 1)
     if [[ -z $active_session ]]; then
-        echo "ERROR: no active tmux session ..." >&2
+        echo "ERROR: No active tmux session ..." >&2
         return $no_active_tmux_session
     fi
     tmux display-popup -E -t "$active_session" \
-        -T "#[align=centre] REMINDER " -S $style -s $style \
+        -T '#[align=centre] REMINDER ' -S $style -s $style \
         -w $width -h $heigth "$popup_body"
 }
 
@@ -112,6 +112,6 @@ else
 Invalid syntax ...
 Try 'remind --help' for more information.
 EOF
-    (exit "$invalid_syntax")
+    (exit $invalid_syntax)
 fi
 
